version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3030"
    volumes:
      - nodeapidata:/app/data/
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: test
      MONGO_DB_USER: root
      MONGO_DB_PASS: test

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test
    volumes:
      - 'mongodbdata:/data/db'

volumes:
  mongodbdata:
  nodeapidata:
